### ISSUE TITLE
just one question.

### ISSUE THREAD

**Issue by wingjjzhang** [kmbang/UnityNativeEdit#1]
the idea about native edit plugin is good!
I find that if I use your editor(android platform)，the other widget something like buttons/toggles can not work any more, I check your native java code,  It seems that a mainlayout was added to the rootlayout, is it the reason make a mask above the unity view?
waiting for your reback.
thx for your job.
![qq20150608-1](https://cloud.githubusercontent.com/assets/1394748/8024783/13eb9514-0d72-11e5-855a-615c29d82b73.jpg)

**Comment by kmbang** [comment]
You mean the other widget in unity UI such as Canvas, Button? I used native edit plugin with Unity UI elements and it seemed it worked okay. Could you elaborate the issue a bit more? Yes, the reason why I added new layout is to separate  plugin from other unity component. Any suggestion will be very welcomed!

**Comment by wingjjzhang** [comment]
hi, I fixed it, the mainLayout turn "clickenable" on, just turn it off.
thx for your back, good job!! 
and I have make a native edit for NGUI base on yours.
![qq20150609-1](https://cloud.githubusercontent.com/assets/1394748/8050206/cd25a266-0e9b-11e5-8cf7-6ff28e6688d2.jpg)

**Comment by wingjjzhang** [comment]
hi,sorry that, I try your original code, it worked today, I don't know, .... thx you.

**Comment by wingjjzhang** [comment]
hi,sorry that, I try your original code, it worked today, I don't know, .... thx you.

**Comment by wingjjzhang** [comment]
hi,sorry that, I try your original code, it worked today, I don't know, .... thx you.

**Comment by wingjjzhang** [comment]
hi,sorry that, I try your original code, it worked today, I don't know, .... thx you.
