### ISSUE TITLE
Adding OnEdit Handler via code

### ISSUE THREAD

**Issue by animepauly** [kmbang/UnityNativeEdit#2]
Hi! First I want to say thanks a lot for this plugin! It works really great but I have one problem. I have a bunch of Input Fields in assets within asset bundles that I want to use your NativeEditBox for, but asset bundles for iOS will not allow me to attach code to a prefab nor hook up these events. So how I was doing it before was this:

``` C#
inputText.onEndEdit.AddListener(delegate{_inputFieldOnEndEditHandler(inputText.text);});
```

But your script looks like it's hijacking this event and passing the string into it instead. So I am unsure how I would add my listener via code since the inputText.text won't give me what I want when I user your way. Also bear in mind I need this to work in the editor as well so passing in the GetNativeText() won't work either.

**Comment by animepauly** [comment]
So I have a hacky solution that seems to work but it's not great if I have to put all of these #if statements in, BUT it works. Hoping for a more elegant solution.

``` C#
#if UNITY_EDITOR
__inputText.onEndEdit.AddListener(delegate{_inputFieldOnEndEditHandler(__inputText, __inputText.text);});
#elif UNITY_IOS
NativeEditBox __nativeEditBox = __inputText.gameObject.GetComponent<NativeEditBox>();
__inputText.onEndEdit.AddListener(delegate{_inputFieldOnEndEditHandler(__inputText, __nativeEditBox.GetTextNative());});
#endif
```

**Comment by animepauly** [comment]
Not sure if this has anything to do with how I am adding the event listeners programmatically or not, but I am getting an error in Xcode when trying to call SetTextNative();

Heres my code where it's failing:

``` C#
#if UNITY_EDITOR
__inputText.text = __userDataVO.FirstNameStr;
#elif UNITY_IOS
__nativeEditBox.SetTextNative(__userDataVO.FirstNameStr);
#endif
```

I know that the __nativeEditBox is not null because I log it out before this call and same goes for __userDataVO.FirstNameStr, which the line in the editor works just fine and this code was working before I updated it to the NativeEditBox. I can't place your script on their directly nor can I add the event listeners because you can't add scripts to prefabs in iOS asset bundles.

Here's the error from Xcode:
NullReferenceException: A null value was found where an object instance was required.
  at MeshCombineUtility.CopyColors (Int32 vertexcount, UnityEngine.Color[] src, UnityEngine.Color[] dst, Int32& offset) [0x00000] in <filename unknown>:0 
  at PluginMsgReceiver.SendPluginMsg (.JsonObject jsonMsg) [0x00000] in <filename unknown>:0 
  at NativeEditBox.SetTextNative (System.String newText) [0x00000] in <filename unknown>:0 
  at adquizition.quizapp.Usernamepanelview._fillInTextIfDataExists (IFormTextInputDataVO __formDataVO, UnityEngine.UI.InputField __inputText, .NativeEditBox __nativeEditBox, IUserDataVO __userDataVO) [0x00000] in <filename unknown>:0 
  at adquizition.quizapp.Usernamepanelview.UpdateFormTextInputData (System.Collections.Generic.List`1 __formTextInputDataVOList, IUserDataVO __userDataVO) [0x00000] in <filename unknown>:0 
  at adquizition.quizapp.UserNameMediator._fulfillUserNameFormDataListHandler (System.Collections.Generic.List`1 __formTextInputDataVOList, IUserDataVO __userDataVO) [0x00000] in <filename unknown>:0 
  at DragRigidbody.Main () [0x00000] in <filename unknown>:0 
  at MeshCombineUtility.CopyColors (Int32 vertexcount, UnityEngine.Color[] src, UnityEngine.Color[] dst, Int32& offset) [0x00000] in <filename unknown>:0 
  at DragRigidbody.Main () [0x00000] in <filename unknown>:0 
  at adquizition.quizapp.GetUserNameFormDataCommand._getUserNameFormList (System.Collections.Generic.List`1 __dataList) [0x00000] in <filename unknown>:0 
  at adquizition.quizapp.GetUserNameFormDataCommand+<_getuserNameFormFromCloud>c__Iterator48.MoveNext () [0x00000] in <filename unknown>:0 
  at System.Action`3[System.Collections.Generic.List`1[System.Object],System.Collections.Generic.Dictionary`2[System.String,System.Object],System.Collections.Generic.Dictionary`2[System.String,System.Object]].EndInvoke (IAsyncResult result) [0x00000] in <filename unknown>:0 
System.Action`3:EndInvoke(IAsyncResult)

**Comment by animepauly** [comment]
So I have more info regarding this. On your SetTextNative() method, I logged the json obj after it was created and it's somehow null:

``` C#
public void SetTextNative(string newText)
{
    JsonObject jsonMsg = new JsonObject();

    jsonMsg["msg"] = MSG_SET_TEXT;
    jsonMsg["text"] = newText;
    Debug.Log ("SetTextNative::jsonMsg = "+jsonMsg); //this is loggin as null somehow
    this.SendPluginMsg(jsonMsg);
}
//in PluginsMsgHandler
protected JsonObject SendPluginMsg(JsonObject jsonMsg)
{
    Debug.Log ("msgHandler = "+msgHandler); //logs as "msgHandler = "
    Debug.Log ("nReceiverId = "+nReceiverId);// logs as "0"
    Debug.Log ("jsonMsg = "+jsonMsg);//logs as "jsonMsg = null"
    return msgHandler.SendMsgToPlugin(nReceiverId, jsonMsg);
}
```

Once again, I am unsure as to if the way I am adding event listeners to this is causing the problem or it's something else. But I don't understand how the jsonMsg is null after it's instantiated

**Comment by kmbang** [comment]
Hi Thank you for brining this issue. As I'm travelling now, i dont have access to the code. Will take a look at and get back to you over the weekend!!

**Comment by animepauly** [comment]
Awesome, and thanks! I removed the event listeners I was adding and am just trying to call SetNativeText() and am still getting this issue. Not sure how jsonMsg is null after instantiation.

**Comment by animepauly** [comment]
I don't want to make this another issue in case it's in there and I don't understand how to do this currently, but how do you close the keyboard on mobile without pressing the done button? I have a login screen where if the user clicks login without closing the keyboard, it just stays open. When using the Unity input field the keyboard closes when the input field loses focus, so I would like the plugin to either behave the same way or allow me to make a call via your plugin msg handler to close it.

**Comment by kmbang** [comment]
Hi Paul,

I just came back from travel. And start looking at the code. 
For runtime eventhandler, you're right that I didn't take into account that there could be custom event handler. I made a naive assumption that it would be fine just to pass the string into onEndEdit. I will try some other way to incorporate your need and try to get back to you when I have more time early next week. 'jsonMsg null' is pretty strange and I never had that problem before. Did you run my 'demo scene' on the Xcode as well? There is 'SetText' button which is to call SetNativeText function. Did you encounter same 'null' issue when you test the demo scene? Btw, it might be related to runtime event handler. I'll do more research on that.

**Comment by kmbang** [comment]
And for closing keyboard, in iOS I put 'default' Done button as IOS support UIBarItem pretty good. However I haven't found any thing in Android as elegant as UIBarItem attached to the keyboard. 
So I didn't implement the 'Done' button yet on Android. I was gonna add it later on.

By the way, it's still supposed to hide the keyboard once it loses focus on the input field.
Does it happen on iOS or Android? On Android,

``` Java
edit.setOnFocusChangeListener(new View.OnFocusChangeListener() {
                @Override
                public void onFocusChange(View v, boolean hasFocus) {
                    if (!hasFocus) {
                        // your action here
                        JSONObject jsonToUnity = new JSONObject();
                        try
                        {
                            jsonToUnity.put("msg", MSG_TEXT_END_EDIT);
                            jsonToUnity.put("text", eb.GetText());
                        }
                        catch(JSONException e) {}
                        eb.SendJsonToUnity(jsonToUnity);
                        eb.showKeyboard(false); 
                    }
                }
```

**Comment by kmbang** [comment]
Oh I just found out that I forgot to add the equivalent code in iOS code.
If you have issue in iOS, that's my fault. Will fix it and update it soon. (sometime early next week along with runtime event handler)

**Comment by kmbang** [comment]
Btw, thanks for you feedback, Paul.

**Comment by animepauly** [comment]
I ran your demo in xcode and on my phone and it worked fine. I also didn't add the runtime event handler when I was getting that json msg = null problem, BUT I did add NativeEditBox to the input filed gameobject via runtime which your demo does not do. The keyboard does not close on iOS unless you tap the done button.

**Comment by kmbang** [comment]
I just committed new update to reflect this issue. 
I confirmed that there was bug when NativeEditBox is runtime-created. Also, closing keyboard in iOS as well. You may just download the '/release'

**Comment by animepauly** [comment]
Awesome! Thanks! I will update this later this week and get back to you. Thanks again for the fixes.

**Comment by animepauly** [comment]
This works as it should now, thanks! Closing the issue.
